# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestYellowbeeswax():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_yellowbeeswax(self):
    self.driver.get("https://www.brambleberry.com/shop-by-product/ingredients/waxes/premium-yellow-beeswax/V001192.html")
    self.driver.set_window_size(1213, 752)
    self.driver.find_element(By.ID, "CybotCookiebotDialogBodyUnderlay").click()
    self.driver.find_element(By.ID, "CybotCookiebotDialogBodyUnderlay").click()
    element = self.driver.find_element(By.ID, "CybotCookiebotDialogBodyUnderlay")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "CybotCookiebotDialogBodyUnderlay").click()
    self.driver.find_element(By.ID, "CybotCookiebotDialogBodyUnderlay").click()
    self.driver.find_element(By.ID, "CybotCookiebotDialogBodyUnderlay").click()
    self.driver.find_element(By.ID, "CybotCookiebotDialogBodyUnderlay").click()
    self.driver.find_element(By.ID, "CybotCookiebotDialogBodyUnderlay").click()
    element = self.driver.find_element(By.ID, "CybotCookiebotDialogBodyUnderlay")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "CybotCookiebotDialogBodyUnderlay").click()
    self.driver.find_element(By.ID, "CybotCookiebotDialogBodyUnderlay").click()
    self.driver.find_element(By.ID, "CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll").click()
    element = self.driver.find_element(By.ID, "CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.LINK_TEXT, "5 lbs").click()
    self.driver.find_element(By.ID, "add-to-cart").click()
    element = self.driver.find_element(By.ID, "add-to-cart")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".minicart-quantity").click()
    self.driver.execute_script("window.scrollTo(0,7)")
    self.driver.execute_script("window.scrollTo(0,69)")
    element = self.driver.find_element(By.LINK_TEXT, "Calculate")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.LINK_TEXT, "Calculate").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "dwfrm_shippingestimator_shippingestimate_zipcode").click()
    self.driver.find_element(By.ID, "dwfrm_shippingestimator_shippingestimate_zipcode").send_keys("92673")
    self.driver.find_element(By.NAME, "dwfrm_cart_estimate").click()
    self.driver.execute_script("window.scrollTo(0,26)")
    self.driver.find_element(By.CSS_SELECTOR, ".order-shipping > .align-right").click()
    self.driver.find_element(By.CSS_SELECTOR, ".order-value").click()
  
