# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestYahoosomething():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_yahoosomething(self):
    self.driver.get("https://www.yahoo.com/")
    self.driver.set_window_size(1843, 763)
    self.driver.find_element(By.ID, "root_3").click()
    self.driver.find_element(By.ID, "yfin-usr-qry").click()
    self.driver.find_element(By.ID, "yfin-usr-qry").send_keys("tsla")
    self.driver.find_element(By.ID, "yfin-usr-qry").send_keys(Keys.ENTER)
    self.driver.execute_script("window.scrollTo(0,102)")
    self.vars["x"] = self.driver.find_element(By.CSS_SELECTOR, ".Fz\\(36px\\)").text
    print(str(self.vars["x"]))
  
