# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

# great imports!
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By

class WholesaleSuppliesPlus():
    def start(self):
        self.driver = webdriver.Firefox()

    def stop(self):
        self.driver.stop_client() # This needs to be added in order to close the window
        self.driver.quit()

    def run(self):
        self.start()

        # Add product to cart
        self.driver.get("https://www.wholesalesuppliesplus.com/products/beeswax-white-ultra-refined-and-bleached.aspx")
        choices = self.driver.find_elements(By.ID, "ProductPriceIDText")
        product = choices[2] # The third element is the 5lb option
        product.click()
        self.driver.find_element(By.ID, "MainContent_ChildContent_ParentData_btnAddToCart_0").click()

        # Checkout
        self.driver.get("https://www.wholesalesuppliesplus.com/securessl/checkout.aspx")
        # TODO: figure out the cookie situation for this one (goes straight to billing with cookies?)
        # self.driver.find_element(By.ID, "MainContent_btnCheckoutGuest").click()
        
        # Fill out checkout details
        self.driver.find_element(By.ID, "MainContent_txtBillFirstNameNew").click()
        self.driver.find_element(By.ID, "MainContent_txtBillFirstNameNew").click()
        element = self.driver.find_element(By.ID, "MainContent_txtBillFirstNameNew")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.ID, "MainContent_txtBillFirstNameNew").send_keys("Russell")
        self.driver.find_element(By.ID, "MainContent_txtBillLastNameNew").click()
        self.driver.find_element(By.ID, "MainContent_txtBillLastNameNew").send_keys("Tran")
        self.driver.find_element(By.ID, "MainContent_txtBillCompanyNameNew").click()
        self.driver.find_element(By.ID, "MainContent_txtBillCompanyNameNew").send_keys("company_name")
        self.driver.find_element(By.ID, "MainContent_txtBillAddr1New").click()
        self.driver.find_element(By.ID, "MainContent_txtBillAddr1New").send_keys("15 Calle Loyola")
        self.driver.find_element(By.ID, "MainContent_txtBillCityNew").click()
        self.driver.find_element(By.ID, "MainContent_txtBillCityNew").send_keys("San Clemente")
        self.driver.find_element(By.ID, "MainContent_cmbBillStateProvinceNew").click()
        dropdown = self.driver.find_element(By.ID, "MainContent_cmbBillStateProvinceNew")
        dropdown.find_element(By.XPATH, "//option[. = 'California']").click()
        self.driver.find_element(By.CSS_SELECTOR, "#MainContent_cmbBillStateProvinceNew > option:nth-child(9)").click()
        self.driver.find_element(By.ID, "MainContent_txtBillPostalCodeNew").click()
        self.driver.find_element(By.ID, "MainContent_txtBillPostalCodeNew").send_keys("92673")
        self.driver.find_element(By.ID, "MainContent_txtBillEmailNew").click()
        self.driver.find_element(By.ID, "MainContent_txtBillEmailNew").click()
        self.driver.find_element(By.ID, "MainContent_txtBillEmailNew").send_keys("myemail@gmail.com")
        self.driver.find_element(By.ID, "MainContent_txtBillPhoneNew").click()
        self.driver.find_element(By.ID, "MainContent_txtBillPhoneNew").send_keys("(949)-123-4567")
        self.driver.find_element(By.CSS_SELECTOR, ".pt20").click()
        self.driver.find_element(By.ID, "MainContent_txtShipFirstNameNew").click()
        self.driver.find_element(By.ID, "MainContent_txtShipFirstNameNew").send_keys("RussellBilling")
        self.driver.find_element(By.ID, "MainContent_txtShipLastNameNew").send_keys("TranBilling")
        self.driver.find_element(By.ID, "MainContent_txtShipCompanyNameNew").click()
        self.driver.find_element(By.ID, "MainContent_txtShipCompanyNameNew").send_keys("company_name")
        self.driver.find_element(By.ID, "MainContent_txtShipAddr1New").click()
        self.driver.find_element(By.ID, "MainContent_txtShipAddr1New").send_keys("15 Calle Loyola")
        self.driver.find_element(By.ID, "MainContent_txtShipCityNew").click()
        self.driver.find_element(By.ID, "MainContent_txtShipCityNew").send_keys("San Clemente")
        self.driver.find_element(By.ID, "MainContent_cmbShipStateProvinceNew").click()
        dropdown = self.driver.find_element(By.ID, "MainContent_cmbShipStateProvinceNew")
        dropdown.find_element(By.XPATH, "//option[. = 'California']").click()
        self.driver.find_element(By.CSS_SELECTOR, "#MainContent_cmbShipStateProvinceNew > option:nth-child(9)").click()
        self.driver.find_element(By.ID, "MainContent_txtShipPostalCodeNew").click()
        self.driver.find_element(By.ID, "MainContent_txtShipPostalCodeNew").send_keys("92673")
        self.driver.find_element(By.ID, "MainContent_txtShipEmailNew").click()
        self.driver.find_element(By.ID, "MainContent_txtShipEmailNew").click()
        self.driver.find_element(By.ID, "MainContent_txtShipEmailNew").send_keys("myemail@gmail.com")
        self.driver.find_element(By.ID, "MainContent_txtShipPhoneNew").click()
        self.driver.find_element(By.ID, "MainContent_txtShipPhoneNew").send_keys("(949)-123-4567")
        self.driver.find_element(By.CSS_SELECTOR, ".co-forms:nth-child(1)").click()
        self.driver.find_element(By.ID, "MainContent_btnUpdateBillingShippingNew").click()
        self.driver.find_element(By.CSS_SELECTOR, "#MainContent_pnlSubmitOrder > div").click()
        self.driver.find_element(By.CSS_SELECTOR, "#MainContent_pnlSubmitOrder > div").click()
        

        # Scrape the price
        subtotal = self.driver.find_element(By.ID, "MainContent_lblSubTotal").text
        total = self.driver.find_element(By.ID, "MainContent_lblGrandTotal").text

        print("The subtotal is ", subtotal)
        print("The total is ", total)

        self.stop()

if __name__ == "__main__":
    w = WholesaleSuppliesPlus()
    w.run()


